"""Initial migration

Revision ID: f5cc6820dd7d
Revises: 
Create Date: 2026-03-03 09:55:15.061348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5cc6820dd7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_types_code'), 'report_types', ['code'], unique=True)
    op.create_index(op.f('ix_report_types_id'), 'report_types', ['id'], unique=False)
    op.create_table('report_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('report_type_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_cc', sa.Boolean(), nullable=False),
    sa.Column('is_bcc', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_type_id'], ['report_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_recipients_email'), 'report_recipients', ['email'], unique=False)
    op.create_index(op.f('ix_report_recipients_id'), 'report_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_report_recipients_report_type_id'), 'report_recipients', ['report_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_recipients_report_type_id'), table_name='report_recipients')
    op.drop_index(op.f('ix_report_recipients_id'), table_name='report_recipients')
    op.drop_index(op.f('ix_report_recipients_email'), table_name='report_recipients')
    op.drop_table('report_recipients')
    op.drop_index(op.f('ix_report_types_id'), table_name='report_types')
    op.drop_index(op.f('ix_report_types_code'), table_name='report_types')
    op.drop_table('report_types')
    # ### end Alembic commands ###
