"""update invites

Revision ID: b8654f9ba0c1
Revises: d27b11445954
Create Date: 2026-03-08 00:57:53.374570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8654f9ba0c1'
down_revision: Union[str, None] = 'd27b11445954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('invitee_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'invitee_email')
    # ### end Alembic commands ###
